name: Calculateur Vantage Matinal

on:
  schedule:
    - cron: '0 2 * * *'  # Déclenchement automatique à 4h00 du matin (Heure de Paris)
  workflow_dispatch:     # Permet d'avoir le bouton gris pour le lancer manuellement

jobs:
  execution:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Recuperation du code
        uses: actions/checkout@v3

      - name: 2. Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Installation des connecteurs
        run: pip install supabase requests

      - name: 4. Lancement de l'analyse tennis
        run: python vantage_bot.py
