name: Vantage Prime - Analyse WTA

on:
  schedule:
    # Se réveille tous les jours à 04h15 UTC (soit 05h15 ou 06h15 en France selon l'heure d'été)
    - cron: '15 4 * * *'
  workflow_dispatch: # Permet de le lancer manuellement avec un bouton si besoin

jobs:
  execution:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Recuperation du code
        uses: actions/checkout@v3

      - name: 2. Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Installation des connecteurs
        run: |
          python -m pip install --upgrade pip
          pip install requests supabase

      - name: 4. Lancement de l'analyse tennis WTA
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python wta_bot.py
